Sat Jan 20 19:23:39 2018
Linux-4.10.0-35-generic-x86_64-with-debian-stretch-sid
Ren'Py 6.99.13.2919
 

Bootstrap to the start of init.init took 0.10s
Early init took 0.00s
Loader init took 0.01s
Loading error handling took 0.03s

Full traceback:
  File "/home/fiendchain/Downloads/sze-the-game/renpy/bootstrap.py", line 305, in bootstrap
    renpy.main.main()
  File "/home/fiendchain/Downloads/sze-the-game/renpy/main.py", line 365, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "/home/fiendchain/Downloads/sze-the-game/renpy/script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "/home/fiendchain/Downloads/sze-the-game/renpy/script.py", line 756, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=lastfn)
  File "/home/fiendchain/Downloads/sze-the-game/renpy/script.py", line 422, in finish_load
    bad_node.filename, bad_node.linenumber))
ScriptError: Name (u'/home/fiendchain/Downloads/sze-the-game/game/minigames/pong/pong.rpy', 1516436513, 0) is defined twice, at game/minigames/pong/pong.rpy:1 and game/minigames/pong/pong.rpy:1.

While running game code:
ScriptError: Name (u'/home/fiendchain/Downloads/sze-the-game/game/minigames/pong/pong.rpy', 1516436513, 0) is defined twice, at game/minigames/pong/pong.rpy:1 and game/minigames/pong/pong.rpy:1.
Traceback (most recent call last):
  File "/home/fiendchain/Downloads/sze-the-game/renpy/bootstrap.py", line 305, in bootstrap
    renpy.main.main()
  File "/home/fiendchain/Downloads/sze-the-game/renpy/main.py", line 365, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "/home/fiendchain/Downloads/sze-the-game/renpy/script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "/home/fiendchain/Downloads/sze-the-game/renpy/script.py", line 756, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=lastfn)
  File "/home/fiendchain/Downloads/sze-the-game/renpy/script.py", line 422, in finish_load
    bad_node.filename, bad_node.linenumber))
ScriptError: Name (u'/home/fiendchain/Downloads/sze-the-game/game/minigames/pong/pong.rpy', 1516436513, 0) is defined twice, at game/minigames/pong/pong.rpy:1 and game/minigames/pong/pong.rpy:1.
