I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 199, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 439, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 449, in <module>
    renpy.load("_reload-2")
  File "game/classes/AttrDict.rpy", line 9, in __getattr__
    return self[name]
KeyError: '__setstate__'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 199, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 439, in script
    python hide:
  File "/home/fiendchain/Downloads/sze-the-game-orphan/renpy/ast.py", line 826, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/fiendchain/Downloads/sze-the-game-orphan/renpy/python.py", line 1764, in py_exec_bytecode
    exec bytecode in globals, locals
  File "renpy/common/00keymap.rpy", line 449, in <module>
    renpy.load("_reload-2")
  File "/home/fiendchain/Downloads/sze-the-game-orphan/renpy/loadsave.py", line 607, in load
    roots, log = loads(location.load(filename))
  File "/home/fiendchain/Downloads/sze-the-game-orphan/renpy/loadsave.py", line 59, in loads
    return cPickle.loads(s)
  File "game/classes/AttrDict.rpy", line 9, in __getattr__
    return self[name]
KeyError: '__setstate__'

Linux-4.10.0-35-generic-x86_64-with-debian-stretch-sid
Ren'Py 6.99.13.2919
sze-the game 0.0
